### ISSUE TITLE
Any plans to support RAML 1.0?

### ISSUE THREAD

**Issue by sichvoge** [ozwolf-software/dropwizard-raml-view#9]
Hi,

First - thanks a lot for the contribution! QQ: Are you planning on supporting RAML 1.0?

Christian

**Comment by OzWolf** [comment]
Hi, my intention is to upgrade to RAML 1.0 support.  Planning my approach for this one and which versions of DW will support it (most likely 0.9 and 1.0).

I also don't want to just terminate RAML 0.8 support so it's going to be fun.

Really need to get my artifact repo solution in place so people don't have to checkout branches and self-compile.

**Comment by sichvoge** [comment]
Sounds very good! Let me know if you need help understanding things on RAML 1.0.

**Comment by sichvoge** [comment]
Hi the new RAML parser allows parsing for 0.8 and 1.0. ;) No need to terminate anything :)

**Comment by OzWolf** [comment]
I have upgraded the bundle to use the new RAML Parser 2 library from Mulesoft.  It supports RAML 1.0, but is possibly missing implementation of a lot of RAML 1.0 features (as it currently does a 1-to-1 mapping of 0.8 and 1.0 properties, and even then RAML 0.8 was not 100% covered).

Version 1.0.2.0 in Maven Central will give you 1.0 functionality.
